# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from alexasomba_paystack.models.charge_submit_pin_response_data_authorization import ChargeSubmitPinResponseDataAuthorization
from alexasomba_paystack.models.charge_submit_pin_response_data_customer import ChargeSubmitPinResponseDataCustomer
from typing import Optional, Set
from typing_extensions import Self

class ChargeSubmitPinResponseData(BaseModel):
    """
    ChargeSubmitPinResponseData
    """ # noqa: E501
    status: StrictStr
    amount: StrictInt
    currency: StrictStr
    transaction_date: StrictStr
    reference: StrictStr
    domain: StrictStr
    redirect_url: Optional[StrictStr]
    metadata: Dict[str, Any]
    gateway_response: StrictStr
    message: Optional[StrictStr]
    channel: StrictStr
    fees: Optional[StrictInt]
    authorization: ChargeSubmitPinResponseDataAuthorization
    customer: ChargeSubmitPinResponseDataCustomer
    __properties: ClassVar[List[str]] = ["status", "amount", "currency", "transaction_date", "reference", "domain", "redirect_url", "metadata", "gateway_response", "message", "channel", "fees", "authorization", "customer"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChargeSubmitPinResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of authorization
        if self.authorization:
            _dict['authorization'] = self.authorization.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # set to None if redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.redirect_url is None and "redirect_url" in self.model_fields_set:
            _dict['redirect_url'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if fees (nullable) is None
        # and model_fields_set contains the field
        if self.fees is None and "fees" in self.model_fields_set:
            _dict['fees'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChargeSubmitPinResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "transaction_date": obj.get("transaction_date"),
            "reference": obj.get("reference"),
            "domain": obj.get("domain"),
            "redirect_url": obj.get("redirect_url"),
            "metadata": obj.get("metadata"),
            "gateway_response": obj.get("gateway_response"),
            "message": obj.get("message"),
            "channel": obj.get("channel"),
            "fees": obj.get("fees"),
            "authorization": ChargeSubmitPinResponseDataAuthorization.from_dict(obj["authorization"]) if obj.get("authorization") is not None else None,
            "customer": ChargeSubmitPinResponseDataCustomer.from_dict(obj["customer"]) if obj.get("customer") is not None else None
        })
        return _obj


