# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from alexasomba_paystack.models.miscellaneous_list_countries_response_array_relationships_currency import MiscellaneousListCountriesResponseArrayRelationshipsCurrency
from alexasomba_paystack.models.miscellaneous_list_countries_response_array_relationships_integration_feature import MiscellaneousListCountriesResponseArrayRelationshipsIntegrationFeature
from alexasomba_paystack.models.miscellaneous_list_countries_response_array_relationships_integration_type import MiscellaneousListCountriesResponseArrayRelationshipsIntegrationType
from typing import Optional, Set
from typing_extensions import Self

class MiscellaneousListCountriesResponseArrayRelationships(BaseModel):
    """
    MiscellaneousListCountriesResponseArrayRelationships
    """ # noqa: E501
    currency: MiscellaneousListCountriesResponseArrayRelationshipsCurrency
    integration_feature: MiscellaneousListCountriesResponseArrayRelationshipsIntegrationFeature
    integration_type: MiscellaneousListCountriesResponseArrayRelationshipsIntegrationType
    payment_method: MiscellaneousListCountriesResponseArrayRelationshipsIntegrationType
    __properties: ClassVar[List[str]] = ["currency", "integration_feature", "integration_type", "payment_method"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MiscellaneousListCountriesResponseArrayRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of currency
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        # override the default output from pydantic by calling `to_dict()` of integration_feature
        if self.integration_feature:
            _dict['integration_feature'] = self.integration_feature.to_dict()
        # override the default output from pydantic by calling `to_dict()` of integration_type
        if self.integration_type:
            _dict['integration_type'] = self.integration_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment_method
        if self.payment_method:
            _dict['payment_method'] = self.payment_method.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MiscellaneousListCountriesResponseArrayRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": MiscellaneousListCountriesResponseArrayRelationshipsCurrency.from_dict(obj["currency"]) if obj.get("currency") is not None else None,
            "integration_feature": MiscellaneousListCountriesResponseArrayRelationshipsIntegrationFeature.from_dict(obj["integration_feature"]) if obj.get("integration_feature") is not None else None,
            "integration_type": MiscellaneousListCountriesResponseArrayRelationshipsIntegrationType.from_dict(obj["integration_type"]) if obj.get("integration_type") is not None else None,
            "payment_method": MiscellaneousListCountriesResponseArrayRelationshipsIntegrationType.from_dict(obj["payment_method"]) if obj.get("payment_method") is not None else None
        })
        return _obj


