# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MiscellaneousListBanksResponseArray(BaseModel):
    """
    MiscellaneousListBanksResponseArray
    """ # noqa: E501
    name: StrictStr
    slug: StrictStr
    code: StrictStr
    longcode: StrictStr
    gateway: Optional[StrictStr]
    pay_with_bank: StrictBool
    supports_transfer: StrictBool
    available_for_direct_debit: StrictBool
    active: StrictBool
    is_deleted: Optional[StrictBool]
    country: StrictStr
    currency: StrictStr
    type: StrictStr
    id: StrictInt
    created_at: StrictStr = Field(validation_alias=AliasChoices('created_at', 'createdAt'), serialization_alias='createdAt')
    updated_at: StrictStr = Field(validation_alias=AliasChoices('updated_at', 'updatedAt'), serialization_alias='updatedAt')
    __properties: ClassVar[List[str]] = ["name", "slug", "code", "longcode", "gateway", "pay_with_bank", "supports_transfer", "available_for_direct_debit", "active", "is_deleted", "country", "currency", "type", "id", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MiscellaneousListBanksResponseArray from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if gateway (nullable) is None
        # and model_fields_set contains the field
        if self.gateway is None and "gateway" in self.model_fields_set:
            _dict['gateway'] = None

        # set to None if is_deleted (nullable) is None
        # and model_fields_set contains the field
        if self.is_deleted is None and "is_deleted" in self.model_fields_set:
            _dict['is_deleted'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MiscellaneousListBanksResponseArray from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "code": obj.get("code"),
            "longcode": obj.get("longcode"),
            "gateway": obj.get("gateway"),
            "pay_with_bank": obj.get("pay_with_bank"),
            "supports_transfer": obj.get("supports_transfer"),
            "available_for_direct_debit": obj.get("available_for_direct_debit"),
            "active": obj.get("active"),
            "is_deleted": obj.get("is_deleted"),
            "country": obj.get("country"),
            "currency": obj.get("currency"),
            "type": obj.get("type"),
            "id": obj.get("id"),
            "created_at": obj.get("created_at") if obj.get("created_at") is not None else obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


