# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PaymentRequestCreateResponseData(BaseModel):
    """
    PaymentRequestCreateResponseData
    """ # noqa: E501
    id: StrictInt
    integration: StrictInt
    domain: StrictStr
    amount: StrictInt
    currency: StrictStr
    due_date: Optional[StrictStr]
    has_invoice: StrictBool
    invoice_number: Optional[StrictInt]
    description: Optional[StrictStr]
    line_items: List[Any]
    tax: List[Any]
    request_code: StrictStr
    status: StrictStr
    paid: StrictBool
    metadata: Optional[Dict[str, Any]]
    notifications: List[Any]
    offline_reference: StrictStr
    customer: StrictInt
    created_at: StrictStr
    discount: Optional[Any]
    split_code: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["id", "integration", "domain", "amount", "currency", "due_date", "has_invoice", "invoice_number", "description", "line_items", "tax", "request_code", "status", "paid", "metadata", "notifications", "offline_reference", "customer", "created_at", "discount", "split_code"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentRequestCreateResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if due_date (nullable) is None
        # and model_fields_set contains the field
        if self.due_date is None and "due_date" in self.model_fields_set:
            _dict['due_date'] = None

        # set to None if invoice_number (nullable) is None
        # and model_fields_set contains the field
        if self.invoice_number is None and "invoice_number" in self.model_fields_set:
            _dict['invoice_number'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if discount (nullable) is None
        # and model_fields_set contains the field
        if self.discount is None and "discount" in self.model_fields_set:
            _dict['discount'] = None

        # set to None if split_code (nullable) is None
        # and model_fields_set contains the field
        if self.split_code is None and "split_code" in self.model_fields_set:
            _dict['split_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentRequestCreateResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "integration": obj.get("integration"),
            "domain": obj.get("domain"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "due_date": obj.get("due_date"),
            "has_invoice": obj.get("has_invoice"),
            "invoice_number": obj.get("invoice_number"),
            "description": obj.get("description"),
            "line_items": obj.get("line_items"),
            "tax": obj.get("tax"),
            "request_code": obj.get("request_code"),
            "status": obj.get("status"),
            "paid": obj.get("paid"),
            "metadata": obj.get("metadata"),
            "notifications": obj.get("notifications"),
            "offline_reference": obj.get("offline_reference"),
            "customer": obj.get("customer"),
            "created_at": obj.get("created_at"),
            "discount": obj.get("discount"),
            "split_code": obj.get("split_code")
        })
        return _obj


