# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from alexasomba_paystack.models.refund_fetch_response_data_customer import RefundFetchResponseDataCustomer
from typing import Optional, Set
from typing_extensions import Self

class RefundFetchResponseData(BaseModel):
    """
    RefundFetchResponseData
    """ # noqa: E501
    integration: StrictInt
    transaction: StrictInt
    dispute: Optional[Any]
    settlement: Optional[Any]
    id: StrictInt
    domain: StrictStr
    currency: StrictStr
    amount: StrictInt
    status: StrictStr
    refunded_at: Optional[Any]
    refunded_by: StrictStr
    customer_note: StrictStr
    merchant_note: StrictStr
    deducted_amount: StrictInt
    fully_deducted: StrictInt
    created_at: StrictStr = Field(validation_alias=AliasChoices('created_at', 'createdAt'), serialization_alias='createdAt')
    bank_reference: Optional[Any]
    transaction_reference: StrictStr
    reason: StrictStr
    customer: RefundFetchResponseDataCustomer
    refund_type: StrictStr
    transaction_amount: StrictInt
    initiated_by: StrictStr
    refund_channel: StrictStr
    session_id: Optional[Any]
    collect_account_number: StrictBool
    __properties: ClassVar[List[str]] = ["integration", "transaction", "dispute", "settlement", "id", "domain", "currency", "amount", "status", "refunded_at", "refunded_by", "customer_note", "merchant_note", "deducted_amount", "fully_deducted", "createdAt", "bank_reference", "transaction_reference", "reason", "customer", "refund_type", "transaction_amount", "initiated_by", "refund_channel", "session_id", "collect_account_number"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RefundFetchResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # set to None if dispute (nullable) is None
        # and model_fields_set contains the field
        if self.dispute is None and "dispute" in self.model_fields_set:
            _dict['dispute'] = None

        # set to None if settlement (nullable) is None
        # and model_fields_set contains the field
        if self.settlement is None and "settlement" in self.model_fields_set:
            _dict['settlement'] = None

        # set to None if refunded_at (nullable) is None
        # and model_fields_set contains the field
        if self.refunded_at is None and "refunded_at" in self.model_fields_set:
            _dict['refunded_at'] = None

        # set to None if bank_reference (nullable) is None
        # and model_fields_set contains the field
        if self.bank_reference is None and "bank_reference" in self.model_fields_set:
            _dict['bank_reference'] = None

        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict['session_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RefundFetchResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "integration": obj.get("integration"),
            "transaction": obj.get("transaction"),
            "dispute": obj.get("dispute"),
            "settlement": obj.get("settlement"),
            "id": obj.get("id"),
            "domain": obj.get("domain"),
            "currency": obj.get("currency"),
            "amount": obj.get("amount"),
            "status": obj.get("status"),
            "refunded_at": obj.get("refunded_at"),
            "refunded_by": obj.get("refunded_by"),
            "customer_note": obj.get("customer_note"),
            "merchant_note": obj.get("merchant_note"),
            "deducted_amount": obj.get("deducted_amount"),
            "fully_deducted": obj.get("fully_deducted"),
            "created_at": obj.get("created_at") if obj.get("created_at") is not None else obj.get("createdAt"),
            "bank_reference": obj.get("bank_reference"),
            "transaction_reference": obj.get("transaction_reference"),
            "reason": obj.get("reason"),
            "customer": RefundFetchResponseDataCustomer.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "refund_type": obj.get("refund_type"),
            "transaction_amount": obj.get("transaction_amount"),
            "initiated_by": obj.get("initiated_by"),
            "refund_channel": obj.get("refund_channel"),
            "session_id": obj.get("session_id"),
            "collect_account_number": obj.get("collect_account_number")
        })
        return _obj


