# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from alexasomba_paystack.models.split_subaccounts import SplitSubaccounts
from typing import Optional, Set
from typing_extensions import Self

class SplitCreate(BaseModel):
    """
    Split configuration for transactions 
    """ # noqa: E501
    name: StrictStr = Field(description="Name of the transaction split")
    type: StrictStr = Field(description="The type of transaction split you want to create.")
    subaccounts: List[SplitSubaccounts] = Field(description="A list of object containing subaccount code and number of shares")
    currency: StrictStr = Field(description="The transaction currency")
    bearer_type: Optional[StrictStr] = Field(default=None, description="This allows you specify how the transaction charge should be processed")
    bearer_subaccount: Optional[StrictStr] = Field(default=None, description="This is the subaccount code of the customer or partner that would bear the transaction charge if you specified subaccount as the bearer type")
    __properties: ClassVar[List[str]] = ["name", "type", "subaccounts", "currency", "bearer_type", "bearer_subaccount"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['percentage', 'flat']):
            raise ValueError("must be one of enum values ('percentage', 'flat')")
        return value

    @field_validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['NGN', 'GHS', 'ZAR', 'USD']):
            raise ValueError("must be one of enum values ('NGN', 'GHS', 'ZAR', 'USD')")
        return value

    @field_validator('bearer_type')
    def bearer_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['subaccount', 'account', 'all-proportional', 'all']):
            raise ValueError("must be one of enum values ('subaccount', 'account', 'all-proportional', 'all')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SplitCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in subaccounts (list)
        _items = []
        if self.subaccounts:
            for _item_subaccounts in self.subaccounts:
                if _item_subaccounts:
                    _items.append(_item_subaccounts.to_dict())
            _dict['subaccounts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SplitCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "subaccounts": [SplitSubaccounts.from_dict(_item) for _item in obj["subaccounts"]] if obj.get("subaccounts") is not None else None,
            "currency": obj.get("currency"),
            "bearer_type": obj.get("bearer_type"),
            "bearer_subaccount": obj.get("bearer_subaccount")
        })
        return _obj


