# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from alexasomba_paystack.models.storefront_contacts_array import StorefrontContactsArray
from typing import Optional, Set
from typing_extensions import Self

class StorefrontCreateResponseData(BaseModel):
    """
    StorefrontCreateResponseData
    """ # noqa: E501
    social_media: List[Any]
    contacts: List[StorefrontContactsArray]
    name: StrictStr
    slug: StrictStr
    currency: StrictStr
    welcome_message: Optional[Any]
    success_message: Optional[Any]
    redirect_url: Optional[Any]
    description: Optional[Any]
    delivery_note: StrictStr
    background_color: StrictStr
    status: StrictStr
    shippable: StrictBool
    integration: StrictInt
    domain: StrictStr
    digital_product_expiry: Optional[Any]
    metadata: Optional[Dict[str, Any]] = None
    id: StrictInt
    created_at: StrictStr = Field(validation_alias=AliasChoices('created_at', 'createdAt'), serialization_alias='createdAt')
    updated_at: StrictStr = Field(validation_alias=AliasChoices('updated_at', 'updatedAt'), serialization_alias='updatedAt')
    products: List[Any]
    shipping_fees: List[Any]
    __properties: ClassVar[List[str]] = ["social_media", "contacts", "name", "slug", "currency", "welcome_message", "success_message", "redirect_url", "description", "delivery_note", "background_color", "status", "shippable", "integration", "domain", "digital_product_expiry", "metadata", "id", "createdAt", "updatedAt", "products", "shipping_fees"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StorefrontCreateResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in contacts (list)
        _items = []
        if self.contacts:
            for _item_contacts in self.contacts:
                if _item_contacts:
                    _items.append(_item_contacts.to_dict())
            _dict['contacts'] = _items
        # set to None if welcome_message (nullable) is None
        # and model_fields_set contains the field
        if self.welcome_message is None and "welcome_message" in self.model_fields_set:
            _dict['welcome_message'] = None

        # set to None if success_message (nullable) is None
        # and model_fields_set contains the field
        if self.success_message is None and "success_message" in self.model_fields_set:
            _dict['success_message'] = None

        # set to None if redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.redirect_url is None and "redirect_url" in self.model_fields_set:
            _dict['redirect_url'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if digital_product_expiry (nullable) is None
        # and model_fields_set contains the field
        if self.digital_product_expiry is None and "digital_product_expiry" in self.model_fields_set:
            _dict['digital_product_expiry'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StorefrontCreateResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "social_media": obj.get("social_media"),
            "contacts": [StorefrontContactsArray.from_dict(_item) for _item in obj["contacts"]] if obj.get("contacts") is not None else None,
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "currency": obj.get("currency"),
            "welcome_message": obj.get("welcome_message"),
            "success_message": obj.get("success_message"),
            "redirect_url": obj.get("redirect_url"),
            "description": obj.get("description"),
            "delivery_note": obj.get("delivery_note"),
            "background_color": obj.get("background_color"),
            "status": obj.get("status"),
            "shippable": obj.get("shippable"),
            "integration": obj.get("integration"),
            "domain": obj.get("domain"),
            "digital_product_expiry": obj.get("digital_product_expiry"),
            "metadata": obj.get("metadata"),
            "id": obj.get("id"),
            "created_at": obj.get("created_at") if obj.get("created_at") is not None else obj.get("createdAt"),
            "updated_at": obj.get("updated_at") if obj.get("updated_at") is not None else obj.get("updatedAt"),
            "products": obj.get("products"),
            "shipping_fees": obj.get("shipping_fees")
        })
        return _obj


