# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SubaccountUpdateResponseData(BaseModel):
    """
    SubaccountUpdateResponseData
    """ # noqa: E501
    domain: StrictStr
    subaccount_code: StrictStr
    account_name: Optional[StrictStr] = None
    business_name: StrictStr
    description: StrictStr
    primary_contact_name: StrictStr
    primary_contact_email: StrictStr
    primary_contact_phone: StrictStr
    metadata: StrictStr
    percentage_charge: Union[StrictFloat, StrictInt]
    is_verified: StrictBool
    settlement_bank: StrictStr
    account_number: StrictStr
    settlement_schedule: StrictStr
    active: StrictBool
    migrate: StrictBool
    currency: StrictStr
    product: StrictStr
    id: StrictInt
    integration: StrictInt
    bank: StrictInt
    managed_by_integration: StrictInt
    created_at: StrictStr = Field(validation_alias=AliasChoices('created_at', 'createdAt'), serialization_alias='createdAt')
    updated_at: StrictStr = Field(validation_alias=AliasChoices('updated_at', 'updatedAt'), serialization_alias='updatedAt')
    __properties: ClassVar[List[str]] = ["domain", "subaccount_code", "account_name", "business_name", "description", "primary_contact_name", "primary_contact_email", "primary_contact_phone", "metadata", "percentage_charge", "is_verified", "settlement_bank", "account_number", "settlement_schedule", "active", "migrate", "currency", "product", "id", "integration", "bank", "managed_by_integration", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubaccountUpdateResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if account_name (nullable) is None
        # and model_fields_set contains the field
        if self.account_name is None and "account_name" in self.model_fields_set:
            _dict['account_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubaccountUpdateResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domain": obj.get("domain"),
            "subaccount_code": obj.get("subaccount_code"),
            "account_name": obj.get("account_name"),
            "business_name": obj.get("business_name"),
            "description": obj.get("description"),
            "primary_contact_name": obj.get("primary_contact_name"),
            "primary_contact_email": obj.get("primary_contact_email"),
            "primary_contact_phone": obj.get("primary_contact_phone"),
            "metadata": obj.get("metadata"),
            "percentage_charge": obj.get("percentage_charge"),
            "is_verified": obj.get("is_verified"),
            "settlement_bank": obj.get("settlement_bank"),
            "account_number": obj.get("account_number"),
            "settlement_schedule": obj.get("settlement_schedule"),
            "active": obj.get("active"),
            "migrate": obj.get("migrate"),
            "currency": obj.get("currency"),
            "product": obj.get("product"),
            "id": obj.get("id"),
            "integration": obj.get("integration"),
            "bank": obj.get("bank"),
            "managed_by_integration": obj.get("managed_by_integration"),
            "created_at": obj.get("created_at") if obj.get("created_at") is not None else obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


