# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TerminalGetResponseData(BaseModel):
    """
    TerminalGetResponseData
    """ # noqa: E501
    id: StrictInt
    serial_number: StrictStr
    device_make: Optional[StrictStr]
    terminal_id: StrictStr
    integration: StrictInt
    domain: StrictStr
    name: Optional[StrictStr]
    address: Optional[StrictStr]
    status: StrictStr
    split_code: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["id", "serial_number", "device_make", "terminal_id", "integration", "domain", "name", "address", "status", "split_code"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TerminalGetResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if device_make (nullable) is None
        # and model_fields_set contains the field
        if self.device_make is None and "device_make" in self.model_fields_set:
            _dict['device_make'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if split_code (nullable) is None
        # and model_fields_set contains the field
        if self.split_code is None and "split_code" in self.model_fields_set:
            _dict['split_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TerminalGetResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "serial_number": obj.get("serial_number"),
            "device_make": obj.get("device_make"),
            "terminal_id": obj.get("terminal_id"),
            "integration": obj.get("integration"),
            "domain": obj.get("domain"),
            "name": obj.get("name"),
            "address": obj.get("address"),
            "status": obj.get("status"),
            "split_code": obj.get("split_code")
        })
        return _obj


