# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TransferInitiate(BaseModel):
    """
    Transfer initiation model
    """ # noqa: E501
    amount: StrictInt = Field(description="Amount to transfer in kobo if currency is NGN and pesewas if currency is GHS.")
    recipient: StrictStr = Field(description="The transfer recipient's code")
    reference: Annotated[str, Field(min_length=16, strict=True)] = Field(description="To ensure idempotency, you need to provide e a unique identifier for the request.  The identifier should be a lowercase alphanumeric string with only -,_  symbols allowed. ")
    reason: Optional[StrictStr] = Field(default=None, description="The reason or narration for the transfer.")
    source: StrictStr = Field(description="The source of funds to send from")
    currency: Optional[StrictStr] = Field(default='NGN', description="Specify the currency of the transfer.")
    __properties: ClassVar[List[str]] = ["amount", "recipient", "reference", "reason", "source", "currency"]

    @field_validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NGN', 'ZAR', 'KES', 'GHS']):
            raise ValueError("must be one of enum values ('NGN', 'ZAR', 'KES', 'GHS')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransferInitiate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransferInitiate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "recipient": obj.get("recipient"),
            "reference": obj.get("reference"),
            "reason": obj.get("reason"),
            "source": obj.get("source") if obj.get("source") is not None else 'balance',
            "currency": obj.get("currency") if obj.get("currency") is not None else 'NGN'
        })
        return _obj


