# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from alexasomba_paystack.models.charge_authorization_response_data_log import ChargeAuthorizationResponseDataLog
from alexasomba_paystack.models.transaction_partial_debit_response_data_authorization import TransactionPartialDebitResponseDataAuthorization
from alexasomba_paystack.models.transaction_partial_debit_response_data_customer import TransactionPartialDebitResponseDataCustomer
from typing import Optional, Set
from typing_extensions import Self

class TransactionPartialDebitResponseData(BaseModel):
    """
    TransactionPartialDebitResponseData
    """ # noqa: E501
    amount: StrictInt
    currency: StrictStr
    transaction_date: StrictStr
    status: StrictStr
    reference: StrictStr
    domain: StrictStr
    metadata: StrictStr
    gateway_response: StrictStr
    message: Optional[Any]
    channel: StrictStr
    ip_address: Optional[Any]
    log: Optional[ChargeAuthorizationResponseDataLog]
    fees: StrictInt
    authorization: TransactionPartialDebitResponseDataAuthorization
    customer: TransactionPartialDebitResponseDataCustomer
    plan: StrictInt
    requested_amount: StrictInt
    id: StrictInt
    __properties: ClassVar[List[str]] = ["amount", "currency", "transaction_date", "status", "reference", "domain", "metadata", "gateway_response", "message", "channel", "ip_address", "log", "fees", "authorization", "customer", "plan", "requested_amount", "id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionPartialDebitResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of log
        if self.log:
            _dict['log'] = self.log.to_dict()
        # override the default output from pydantic by calling `to_dict()` of authorization
        if self.authorization:
            _dict['authorization'] = self.authorization.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if ip_address (nullable) is None
        # and model_fields_set contains the field
        if self.ip_address is None and "ip_address" in self.model_fields_set:
            _dict['ip_address'] = None

        # set to None if log (nullable) is None
        # and model_fields_set contains the field
        if self.log is None and "log" in self.model_fields_set:
            _dict['log'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionPartialDebitResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "transaction_date": obj.get("transaction_date"),
            "status": obj.get("status"),
            "reference": obj.get("reference"),
            "domain": obj.get("domain"),
            "metadata": obj.get("metadata"),
            "gateway_response": obj.get("gateway_response"),
            "message": obj.get("message"),
            "channel": obj.get("channel"),
            "ip_address": obj.get("ip_address"),
            "log": ChargeAuthorizationResponseDataLog.from_dict(obj["log"]) if obj.get("log") is not None else None,
            "fees": obj.get("fees"),
            "authorization": TransactionPartialDebitResponseDataAuthorization.from_dict(obj["authorization"]) if obj.get("authorization") is not None else None,
            "customer": TransactionPartialDebitResponseDataCustomer.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "plan": obj.get("plan"),
            "requested_amount": obj.get("requested_amount"),
            "id": obj.get("id")
        })
        return _obj


