# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from alexasomba_paystack.models.transaction_partial_debit_amount import TransactionPartialDebitAmount
from typing import Optional, Set
from typing_extensions import Self

class TransactionPartialDebit(BaseModel):
    """
    TransactionPartialDebit
    """ # noqa: E501
    email: StrictStr = Field(description="Customer's email address")
    amount: TransactionPartialDebitAmount
    authorization_code: StrictStr = Field(description="Valid authorization code to charge")
    currency: StrictStr = Field(description="Specified as NGN or GHS")
    at_least: Optional[StrictStr] = Field(default=None, description="Minimum amount to charge")
    reference: Optional[StrictStr] = Field(default=None, description="Unique transaction reference. Only -, ., = and alphanumeric characters allowed.")
    __properties: ClassVar[List[str]] = ["email", "amount", "authorization_code", "currency", "at_least", "reference"]

    @field_validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['NGN', 'GHS']):
            raise ValueError("must be one of enum values ('NGN', 'GHS')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransactionPartialDebit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransactionPartialDebit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "amount": TransactionPartialDebitAmount.from_dict(obj["amount"]) if obj.get("amount") is not None else None,
            "authorization_code": obj.get("authorization_code"),
            "currency": obj.get("currency"),
            "at_least": obj.get("at_least"),
            "reference": obj.get("reference")
        })
        return _obj


