# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.3.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from alexasomba_paystack.models.transfer_recipient_update_response_data_details import TransferRecipientUpdateResponseDataDetails
from typing import Optional, Set
from typing_extensions import Self

class TransferRecipientUpdateResponseData(BaseModel):
    """
    TransferRecipientUpdateResponseData
    """ # noqa: E501
    type: StrictStr
    name: StrictStr
    metadata: Optional[Dict[str, Any]]
    domain: StrictStr
    details: TransferRecipientUpdateResponseDataDetails
    currency: StrictStr
    recipient_code: StrictStr
    active: StrictBool
    id: StrictInt
    created_at: StrictStr = Field(validation_alias=AliasChoices('created_at', 'createdAt'), serialization_alias='createdAt')
    updated_at: StrictStr = Field(validation_alias=AliasChoices('updated_at', 'updatedAt'), serialization_alias='updatedAt')
    __properties: ClassVar[List[str]] = ["type", "name", "metadata", "domain", "details", "currency", "recipient_code", "active", "id", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransferRecipientUpdateResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of details
        if self.details:
            _dict['details'] = self.details.to_dict()
        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransferRecipientUpdateResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "name": obj.get("name"),
            "metadata": obj.get("metadata"),
            "domain": obj.get("domain"),
            "details": TransferRecipientUpdateResponseDataDetails.from_dict(obj["details"]) if obj.get("details") is not None else None,
            "currency": obj.get("currency"),
            "recipient_code": obj.get("recipient_code"),
            "active": obj.get("active"),
            "id": obj.get("id"),
            "created_at": obj.get("created_at") if obj.get("created_at") is not None else obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


