# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.3.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from alexasomba_paystack.models.transfer_recipient_fetch_response_data_details import TransferRecipientFetchResponseDataDetails
from typing import Optional, Set
from typing_extensions import Self

class TransferRecipientFetchResponseData(BaseModel):
    """
    TransferRecipientFetchResponseData
    """ # noqa: E501
    integration: Optional[StrictInt] = None
    domain: StrictStr
    type: StrictStr
    currency: StrictStr
    name: StrictStr
    details: TransferRecipientFetchResponseDataDetails
    description: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = None
    recipient_code: StrictStr
    active: StrictBool
    recipient_account: Optional[StrictStr] = None
    institution_code: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    id: StrictInt
    is_deleted: Optional[StrictBool] = Field(default=None, alias="isDeleted")
    is_deleted: Optional[StrictBool] = None
    created_at: StrictStr = Field(validation_alias=AliasChoices('created_at', 'createdAt'), serialization_alias='createdAt')
    updated_at: StrictStr = Field(validation_alias=AliasChoices('updated_at', 'updatedAt'), serialization_alias='updatedAt')
    __properties: ClassVar[List[str]] = ["integration", "domain", "type", "currency", "name", "details", "description", "metadata", "recipient_code", "active", "recipient_account", "institution_code", "email", "id", "isDeleted", "is_deleted", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransferRecipientFetchResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of details
        if self.details:
            _dict['details'] = self.details.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if recipient_account (nullable) is None
        # and model_fields_set contains the field
        if self.recipient_account is None and "recipient_account" in self.model_fields_set:
            _dict['recipient_account'] = None

        # set to None if institution_code (nullable) is None
        # and model_fields_set contains the field
        if self.institution_code is None and "institution_code" in self.model_fields_set:
            _dict['institution_code'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransferRecipientFetchResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "integration": obj.get("integration"),
            "domain": obj.get("domain"),
            "type": obj.get("type"),
            "currency": obj.get("currency"),
            "name": obj.get("name"),
            "details": TransferRecipientFetchResponseDataDetails.from_dict(obj["details"]) if obj.get("details") is not None else None,
            "description": obj.get("description"),
            "metadata": obj.get("metadata"),
            "recipient_code": obj.get("recipient_code"),
            "active": obj.get("active"),
            "recipient_account": obj.get("recipient_account"),
            "institution_code": obj.get("institution_code"),
            "email": obj.get("email"),
            "id": obj.get("id"),
            "isDeleted": obj.get("isDeleted"),
            "is_deleted": obj.get("is_deleted"),
            "created_at": obj.get("created_at") if obj.get("created_at") is not None else obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


