# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TransferCreateResponseData(BaseModel):
    """
    TransferCreateResponseData
    """ # noqa: E501
    transfersessionid: List[Any]
    transfertrials: List[Any]
    domain: StrictStr
    amount: StrictInt
    currency: StrictStr
    reference: StrictStr
    source: StrictStr
    source_details: Optional[Any]
    reason: StrictStr
    status: StrictStr
    failures: Optional[Any]
    transfer_code: StrictStr
    titan_code: Optional[Any]
    transferred_at: Optional[Any]
    id: StrictInt
    integration: StrictInt
    request: StrictInt
    recipient: StrictInt
    created_at: StrictStr = Field(validation_alias=AliasChoices('created_at', 'createdAt'), serialization_alias='createdAt')
    updated_at: StrictStr = Field(validation_alias=AliasChoices('updated_at', 'updatedAt'), serialization_alias='updatedAt')
    __properties: ClassVar[List[str]] = ["transfersessionid", "transfertrials", "domain", "amount", "currency", "reference", "source", "source_details", "reason", "status", "failures", "transfer_code", "titan_code", "transferred_at", "id", "integration", "request", "recipient", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransferCreateResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if source_details (nullable) is None
        # and model_fields_set contains the field
        if self.source_details is None and "source_details" in self.model_fields_set:
            _dict['source_details'] = None

        # set to None if failures (nullable) is None
        # and model_fields_set contains the field
        if self.failures is None and "failures" in self.model_fields_set:
            _dict['failures'] = None

        # set to None if titan_code (nullable) is None
        # and model_fields_set contains the field
        if self.titan_code is None and "titan_code" in self.model_fields_set:
            _dict['titan_code'] = None

        # set to None if transferred_at (nullable) is None
        # and model_fields_set contains the field
        if self.transferred_at is None and "transferred_at" in self.model_fields_set:
            _dict['transferred_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransferCreateResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transfersessionid": obj.get("transfersessionid"),
            "transfertrials": obj.get("transfertrials"),
            "domain": obj.get("domain"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "reference": obj.get("reference"),
            "source": obj.get("source"),
            "source_details": obj.get("source_details"),
            "reason": obj.get("reason"),
            "status": obj.get("status"),
            "failures": obj.get("failures"),
            "transfer_code": obj.get("transfer_code"),
            "titan_code": obj.get("titan_code"),
            "transferred_at": obj.get("transferred_at"),
            "id": obj.get("id"),
            "integration": obj.get("integration"),
            "request": obj.get("request"),
            "recipient": obj.get("recipient"),
            "created_at": obj.get("created_at") if obj.get("created_at") is not None else obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


