# coding: utf-8

"""
    Paystack

    The OpenAPI specification of the Paystack API that merchants and developers can harness to build financial solutions in Africa.

    The version of the OpenAPI document: 1.0.0
    Contact: techsupport@paystack.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from alexasomba_paystack.models.virtual_terminal_create_response_data_destinations_inner import VirtualTerminalCreateResponseDataDestinationsInner
from typing import Optional, Set
from typing_extensions import Self

class VirtualTerminalCreateResponseData(BaseModel):
    """
    VirtualTerminalCreateResponseData
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    integration: StrictInt
    domain: StrictStr
    code: StrictStr
    payment_methods: List[Any] = Field(alias="paymentMethods")
    active: StrictBool
    metadata: Optional[Any]
    destinations: List[VirtualTerminalCreateResponseDataDestinationsInner]
    currency: StrictStr
    __properties: ClassVar[List[str]] = ["id", "name", "integration", "domain", "code", "paymentMethods", "active", "metadata", "destinations", "currency"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VirtualTerminalCreateResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in destinations (list)
        _items = []
        if self.destinations:
            for _item_destinations in self.destinations:
                if _item_destinations:
                    _items.append(_item_destinations.to_dict())
            _dict['destinations'] = _items
        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VirtualTerminalCreateResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "integration": obj.get("integration"),
            "domain": obj.get("domain"),
            "code": obj.get("code"),
            "paymentMethods": obj.get("paymentMethods"),
            "active": obj.get("active"),
            "metadata": obj.get("metadata"),
            "destinations": [VirtualTerminalCreateResponseDataDestinationsInner.from_dict(_item) for _item in obj["destinations"]] if obj.get("destinations") is not None else None,
            "currency": obj.get("currency")
        })
        return _obj


